name: Build and Push Frontend

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/riyanamanda/helpdesk-client
                  tags: |
                      type=raw,value=latest
                      type=sha

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  platforms: linux/amd64

                  cache-from: type=gha
                  cache-to: type=gha,mode=max

                  build-args: |
                      VITE_APP_NAME=${{ vars.VITE_APP_NAME }}
                      VITE_API_BASE_URL=
                      VITE_FIREBASE_API_KEY=${{ vars.VITE_FIREBASE_API_KEY }}
                      VITE_FIREBASE_AUTH_DOMAIN=${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
                      VITE_FIREBASE_PROJECT_ID=${{ vars.VITE_FIREBASE_PROJECT_ID }}
                      VITE_FIREBASE_STORAGE_BUCKET=${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
                      VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
                      VITE_FIREBASE_APP_ID=${{ vars.VITE_FIREBASE_APP_ID }}
                      VITE_GOOGLE_CLIENT_ID=${{ vars.VITE_GOOGLE_CLIENT_ID }}

                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Trigger infra deploy
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.INFRA_DISPATCH_TOKEN }}
                  repository: riyanamanda/helpdesk-infra
                  event-type: deploy
                  client-payload: '{"service": "frontend"}'
